---
# tasks file for docker (Ubuntu specific)

- name: Add Docker APT repository key
  become: yes
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  tags:
    - docker

- name: Add Docker APT repository
  become: yes
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ hostvars[inventory_hostname].ansible_lsb.codename }} main'
    state: present
  tags:
    - docker

- name: Install Docker packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ docker_packages }}"
  tags:
    - docker
